services:
  db:
    image: postgres:latest
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  pg_volume: {}
